apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp
  labels:
    app: sampleapp
    release: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: metrics
